-- MySQL Script generated by MySQL Workbench
-- sex 05 nov 2021 12:28:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idusuario` INT NOT NULL,
  `nomeUsuario` VARCHAR(45) NULL,
  `emailUsuario` VARCHAR(45) NULL,
  `senhaUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoriaCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoriaCompra` (
  `idcategoriaCompra` INT NOT NULL AUTO_INCREMENT,
  `descricaoCategoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoriaCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `usuarios_idusuario` INT NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  `descricaoCompra` VARCHAR(45) NULL,
  `localCompra` VARCHAR(45) NULL,
  `categoriaCompra` VARCHAR(45) NULL,
  `flagUrgencia` INT NULL DEFAULT 0,
  PRIMARY KEY (`idCompra`, `usuarios_idusuario`, `categoria_idcategoria`),
  INDEX `fk_compra_usuarios_idx` (`usuarios_idusuario` ASC) VISIBLE,
  INDEX `fk_compra_categoriaCompra1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_compra_usuarios`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `mydb`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_categoriaCompra1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `mydb`.`categoriaCompra` (`idcategoriaCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itensCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itensCompra` (
  `iditensCompra` INT NOT NULL AUTO_INCREMENT,
  `compra_idCompra` INT NOT NULL,
  `itensCompra` VARCHAR(45) NULL,
  `qtdIten` INT NULL,
  `unidadeIten` VARCHAR(45) NULL,
  `precoItem` VARCHAR(45) NULL,
  `flagComprado` VARCHAR(45) NULL DEFAULT 0,
  PRIMARY KEY (`iditensCompra`, `compra_idCompra`),
  INDEX `fk_itensCompra_compra1_idx` (`compra_idCompra` ASC) VISIBLE,
  CONSTRAINT `fk_itensCompra_compra1`
    FOREIGN KEY (`compra_idCompra`)
    REFERENCES `mydb`.`compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
