-- MySQL Script generated by MySQL Workbench
-- qua 03 nov 2021 23:09:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ListPad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ListPad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS ListPad DEFAULT CHARACTER SET utf8 ;
USE ListPad ;

-- -----------------------------------------------------
-- Table ListPad.usuarios
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios (idusuario INTEGER PRIMARY KEY AUTOINCREMENT,  nomeUsuario VARCHAR, emailUsuario VARCHAR, senhaUsuario VARCHAR);

-- -----------------------------------------------------
-- Table ListPad.clientes
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS clientes ( idclientes INTEGER PRIMARY KEY AUTOINCREMENT, nomeCliente VARCHAR, sobreNomeCliente VARCHAR, emailCliente VARCHAR, telefoneCliente VARCHAR, bicicletaCliente VARCHAR);


-- -----------------------------------------------------
-- Table ListPad.revisao
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS revisao (idrevisao INTEGER AUTOINCREMENT, usuarios_idusuario INT NOT NULL, clientes_idclientes INT NOT NULL, descricaoRevisao VARCHAR, flagUrgencia INT NULL,   categoriaRevisao VARCHAR, PRIMARY KEY (idrevisao, usuarios_idusuario, clientes_idclientes), FOREIGN KEY (usuarios_idusuario) REFERENCES usuarios (idusuario) ON DELETE NO ACTION ON UPDATE NO ACTION, FOREIGN KEY (clientes_idclientes) REFERENCES clientes (idclientes) ON DELETE NO ACTION ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table ListPad.itemRevisao
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS itemRevisao (idItemRevisao INTEGER, revisao_idrevisao INTEGER NOT NULL, descricaoItemrevisao VARCHAR, PRIMARY KEY (iditemRevisao, revisao_idrevisao), FOREIGN KEY (revisao_idrevisao) REFERENCES revisao (idrevisao) ON DELETE NO ACTION ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table ListPad.categoriaRevisao
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS categoriaRevisao (idcategoriaRevisao INTEGER, revisao_idrevisao INTEGER, descricaoCategoria VARCHAR, PRIMARY KEY (idcategoriaRevisao, revisao_idrevisao), FOREIGN KEY (revisao_idrevisao) REFERENCES revisao (idrevisao));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
